# Generated by Django 2.2.7 on 2019-11-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('answers', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('often', 'often'), ('not often', 'not often')], max_length=60, verbose_name='answers')),
            ],
        ),
    ]
